### ISSUE TITLE
LSP installation problem

### ISSUE THREAD

**Issue by NEsanya** [leanprover/lean4-mode#16]
When i turn on lean4-mode, i saw this:
```
LSP :: The following servers support current file but do not have automatic installation: lean4-lsp
You may find the installation instructions at https://emacs-lsp.github.io/lsp-mode/page/languages.
(If you have already installed the server check *lsp-log*).
```

What should i do?

System: arch linux
Emacs: emacs 28.1 (native comp) & doom

**Comment by Kha** [comment]
AFAICT this error means that there is no `lean` binary in `exec-path`. Do you have `elan` installed?

**Comment by NEsanya** [comment]
Yes, i do.

Elan version: 1.4.1 (6a7f30d8e 2022-04-15)
Lean version: version 4.0.0-nightly-2022-06-17, commit f0e2696ec82b, Release
Lake version: 3.1.1
