### ISSUE TITLE
Error in post-command-hook (lean4-info-buffer-redisplay-debounced)

### ISSUE THREAD

**Issue by dwrensha** [leanprover/lean4-mode#19]
After #11, I am unable to see the goal in the goal view, and I see the following errors in my `*Messages*` buffer:
```
Error in post-command-hook (lean4-info-buffer-redisplay-debounced): (void-function time-convert)
LSP :: Unable to autoconfigure company-mode. [2 times]
LSP :: lean4-lsp:473680 initialized successfully in folders: (/home/dwrensha/src/mathlib4)
LSP :: Unable to autoconfigure company-mode. [2 times]
Error running timer: (void-function time-convert)
Error running timer ‘lsp--on-idle’: (void-function time-convert) [34 times]
Error processing message (void-function time-convert). [14 times]

```

**Comment by dwrensha** [comment]
cc @bollu

**Comment by Kha** [comment]
Apparently this function was introduced in Emacs 27.1

**Comment by dwrensha** [comment]
Ah, yeah, I'm on `GNU Emacs 26.3`

**Comment by Kha** [comment]
Hmm, that's quite old I have to say! Especially with lsp-mode heavily benefiting from native compilation in Emacs 28 (AFAIK). Are you dependent on 26 by your distribution?

**Comment by dwrensha** [comment]
Yes, I'm using Emacs 26.3 because that's the default on Ubuntu 20.04. (I do hope to update to Ubuntu 22.04 before too long. I think that should be Emacs 27.1.)
