### ISSUE TITLE
Unicode insertion not working

### ISSUE THREAD

**Issue by SpaceTurth** [leanprover/lean4-mode#40]
Hello, I'm newish to emacs and not sure if this is the place to post this. I have lean4-mode installed, and when I open a .lean file and type `#check id` I see the correct type information displayed. However, when I type `\a`, I do not get a unicode "alpha" as expected. What should I do to debug this?

**Comment by Kha** [comment]
At least on Doom Emacs, people have reported that the input method no longer activates automatically. You can try running `M-x set-input-method` manually. I usually use the Doom shortcut `C-\` for `toggle-input-method`.

**Comment by SpaceTurth** [comment]
I'm using a vanilla emacs setup. `M-x set-input-method Lean` worked, I'll just add a hook. Thank you!
