### ISSUE TITLE
Use GPL as license for future changes

### ISSUE THREAD

**Issue by mekeor** [leanprover/lean4-mode#72]
Currently, lean4-mode uses the Apache 2.0 license. [Most Elpa packages are licensed under GPL](https://emacsmirror.net/stats/licenses.html#orga1cb52b) which comes with copyleft, just like Emacs itself, which fits best to the spirit of the Emacs community in my opinion.

I suggest to use the GPLv3+ for future changes of lean4-mode. It would thus be dual-licensed under both Apache-2.0 and GPLv3+. These licenses are compatible in this way. Since GPLv3+ is stricter that Apache-2.0, this would effectively mean that lean4-mode can be treated as if it was under GPLv3+.

**Comment by JLimperg** [comment]
Please don't. The Lean ecosystem is fully on Apache and there are still some companies that refuse to use GPL (for no good reason, imo, but I'm not a lawyer). In any case, there's really no reason for anyone to make a substantial closed-source fork of lean4-mode, which is the scenario that GPL guards against.
